COMP: Remove attempt to find Python 2 and avoid reporting numpy error
This commit avoids reporting the following error:

  -- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.10", minimum required is "2.7")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.10")
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ImportError: No module named numpy.distutils